# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "kubernetes" {
    secret_suffix  = "cert-manager"
    config_path    = "~/.kube/config"
    config_context = "vault-pki"
    namespace      = "terraform"
  }
}
