# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "kubernetes" {
    secret_suffix  = "vault"
    config_path    = "~/.kube/config"
    config_context = "minikube"
    namespace      = "terraform"
  }
}
