---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cert-manager
  name: vault-issuer
---
apiVersion: v1
kind: Secret
metadata:
  namespace: cert-manager
  name: vault-issuer-token
  annotations:
    kubernetes.io/service-account.name: vault-issuer
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: http://vault.default:8200
    path: pki/test-org/v1/ica2/v1/roles/test-dot-com-subdomain
    auth:
      kubernetes:
        role: cert-manager
        serviceAccountRef:
          name: vault-issuer
---
